name: 'Bundlewatch Github Action'
description: 'Run bundlewatch against your PR to keep those bundles in check! Update your package.json according to bundlewatch config'
author: 'Jacky Efendi'
inputs:
  bundlewatch-github-token:
    description: 'A token to authenticate with the Bundlewatch service. Set this as a secret in your GitHub repository'
    required: true
  build-script:
    description: 'Optional — The build script for your project. Will be run before running bundlewatch'
    required: false
  bundlewatch-config:
    description: 'Optional — The path to your external bundlewatch.config.js file. If not provided, it will assume the configuration exist in your package.json file'
    required: false
  branch-base:
    description: 'Optional — The name of the branch to compare against. Usually it is your master/main branch. Defaults to GitHub PR target branch'
    required: false

runs:
  using: 'node16'
  main: 'lib/main.js'
