name: 'Bundlesize Github Action'
description: 'Run bundlesize against your PR to keep those bundles in check! Update your package.json according to bundlesize config'
author: 'Jacky Efendi'
inputs:
  build-script:
    description: 'The build script to run before running bundlesize'
    required: true

runs:
  using: 'node10'
  main: 'lib/main.js'
